# Generated by Django 4.0.5 on 2022-06-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0005_remove_ranking_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='author',
            field=models.CharField(default='user prueba', max_length=30),
            preserve_default=False,
        ),
    ]
