# Generated by Django 4.0.5 on 2022-06-26 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0006_ranking_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userpost',
        ),
    ]
