# Generated by Django 4.0.5 on 2022-06-27 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0014_ranking_post_image_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post_image',
        ),
    ]
