# Generated by Django 4.0.5 on 2022-06-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0015_delete_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='sub_title',
            field=models.CharField(default='prueba subtitulo', max_length=30),
            preserve_default=False,
        ),
    ]
